export const ActionTypes = {
    ADD_USER: 'ADD_USER',
    SAVE_ADD_USER: 'SAVE_ADD_USER',
    GET_ALL_USER: 'GET_ALL_USER',
    RECEIVE_USER: 'RECEIVE_USER',
    GET_USER_ID: 'GET_USER_ID',
    UPDATE_USER: 'UPDATE_USER',
    SAVE_UPDATE_USER: 'SAVE_UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    SAVE_DELETE_USER: 'SAVE_DELETE_USER',
    GET_ALL_ADDRESS: 'GET_ALL_ADDRESS',
    SAVE_ALL_ADDRESS: 'SAVE_ALL_ADDRESS',
};