export const ActionTypes = {
    ADD_USER: 'ADD_USER',
    GET_ALL_USER: 'GET_ALL_USER',
    GET_USER_ID: 'GET_USER_ID',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    GET_ALL_COUNTRY: 'GET_ALL_COUNTRY',
    GET_ALL_CITY: 'GET_ALL_CITY',
    GET_CITY_ID: 'GET_CITY_ID',
    GET_ALL_DISTRICT: 'GET_ALL_DISTRICT',
    GET_DISTRICT_ID: 'GET_DISTRICT_ID',
    GET_ALL_WARD: 'GET_ALL_WARD',
    GET_WARD_ID: 'GET_WARD_ID',
};